name: Build Java Package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Java Project
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Configuration du JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Construction du package et exécution des tests Maven
        run: mvn -B package
